//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QLHDDbContextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QLHDDbContextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLHD.UI.Localization.QLHDDbContextResources", typeof(QLHDDbContextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp Đồng.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội Dung.
        /// </summary>
        public static string Contract_Content {
            get {
                return ResourceManager.GetString("Contract_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà Thầu.
        /// </summary>
        public static string Contract_Contractor {
            get {
                return ResourceManager.GetString("Contract_Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTHĐ Ban Đầu.
        /// </summary>
        public static string Contract_ContractOriginValue {
            get {
                return ResourceManager.GetString("Contract_ContractOriginValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string Contract_CreatedAt {
            get {
                return ResourceManager.GetString("Contract_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string Contract_CreatedBy {
            get {
                return ResourceManager.GetString("Contract_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string Contract_IsActive {
            get {
                return ResourceManager.GetString("Contract_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string Contract_ModifiedAt {
            get {
                return ResourceManager.GetString("Contract_ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string Contract_ModifiedBy {
            get {
                return ResourceManager.GetString("Contract_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Hợp Đồng.
        /// </summary>
        public static string Contract_Name {
            get {
                return ResourceManager.GetString("Contract_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ký.
        /// </summary>
        public static string Contract_SigningDate {
            get {
                return ResourceManager.GetString("Contract_SigningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Thanh Lý.
        /// </summary>
        public static string Contract_TerminateDate {
            get {
                return ResourceManager.GetString("Contract_TerminateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạng Mục.
        /// </summary>
        public static string Contract_Work {
            get {
                return ResourceManager.GetString("Contract_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ lục hợp đồng.
        /// </summary>
        public static string ContractApendix {
            get {
                return ResourceManager.GetString("ContractApendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị điều chỉnh.
        /// </summary>
        public static string ContractApendix_AdjustedValue {
            get {
                return ResourceManager.GetString("ContractApendix_AdjustedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp Đồng.
        /// </summary>
        public static string ContractApendix_Contract {
            get {
                return ResourceManager.GetString("ContractApendix_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string ContractApendix_CreatedAt {
            get {
                return ResourceManager.GetString("ContractApendix_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string ContractApendix_CreatedBy {
            get {
                return ResourceManager.GetString("ContractApendix_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string ContractApendix_Description {
            get {
                return ResourceManager.GetString("ContractApendix_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string ContractApendix_IsActive {
            get {
                return ResourceManager.GetString("ContractApendix_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string ContractApendix_ModifiedAt {
            get {
                return ResourceManager.GetString("ContractApendix_ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string ContractApendix_ModifiedBy {
            get {
                return ResourceManager.GetString("ContractApendix_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Phụ Lục.
        /// </summary>
        public static string ContractApendix_Name {
            get {
                return ResourceManager.GetString("ContractApendix_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ Tự.
        /// </summary>
        public static string ContractApendix_Order {
            get {
                return ResourceManager.GetString("ContractApendix_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ lục hợp đồng.
        /// </summary>
        public static string ContractApendixPlural {
            get {
                return ResourceManager.GetString("ContractApendixPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà thầu.
        /// </summary>
        public static string Contractor {
            get {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ.
        /// </summary>
        public static string Contractor_Address {
            get {
                return ResourceManager.GetString("Contractor_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TK Ngân Hàng Số.
        /// </summary>
        public static string Contractor_BankAccountNo {
            get {
                return ResourceManager.GetString("Contractor_BankAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tại Ngân Hàng.
        /// </summary>
        public static string Contractor_BankName {
            get {
                return ResourceManager.GetString("Contractor_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Nhà Thầu.
        /// </summary>
        public static string Contractor_Code {
            get {
                return ResourceManager.GetString("Contractor_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string Contractor_CreatedAt {
            get {
                return ResourceManager.GetString("Contractor_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string Contractor_CreatedBy {
            get {
                return ResourceManager.GetString("Contractor_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string Contractor_IsActive {
            get {
                return ResourceManager.GetString("Contractor_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string Contractor_ModifiedAt {
            get {
                return ResourceManager.GetString("Contractor_ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string Contractor_ModifiedBy {
            get {
                return ResourceManager.GetString("Contractor_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Nhà Thầu.
        /// </summary>
        public static string Contractor_Name {
            get {
                return ResourceManager.GetString("Contractor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT.
        /// </summary>
        public static string Contractor_PhoneNumber {
            get {
                return ResourceManager.GetString("Contractor_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người Đại Diện.
        /// </summary>
        public static string Contractor_Representative {
            get {
                return ResourceManager.GetString("Contractor_Representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Số Thuế.
        /// </summary>
        public static string Contractor_TaxCode {
            get {
                return ResourceManager.GetString("Contractor_TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà thầu.
        /// </summary>
        public static string ContractorPlural {
            get {
                return ResourceManager.GetString("ContractorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng.
        /// </summary>
        public static string ContractPlural {
            get {
                return ResourceManager.GetString("ContractPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại chi phí.
        /// </summary>
        public static string CostType {
            get {
                return ResourceManager.GetString("CostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string CostType_CreatedAt {
            get {
                return ResourceManager.GetString("CostType_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string CostType_CreatedBy {
            get {
                return ResourceManager.GetString("CostType_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CostType_Id {
            get {
                return ResourceManager.GetString("CostType_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string CostType_IsActive {
            get {
                return ResourceManager.GetString("CostType_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string CostType_ModifiedAt {
            get {
                return ResourceManager.GetString("CostType_ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string CostType_ModifiedBy {
            get {
                return ResourceManager.GetString("CostType_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Loại Chi Phí.
        /// </summary>
        public static string CostType_Name {
            get {
                return ResourceManager.GetString("CostType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại chi phí.
        /// </summary>
        public static string CostTypePlural {
            get {
                return ResourceManager.GetString("CostTypePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string Invoice_CreatedAt {
            get {
                return ResourceManager.GetString("Invoice_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string Invoice_CreatedBy {
            get {
                return ResourceManager.GetString("Invoice_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string Invoice_IsActive {
            get {
                return ResourceManager.GetString("Invoice_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string Invoice_ModifiedAt {
            get {
                return ResourceManager.GetString("Invoice_ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string Invoice_ModifiedBy {
            get {
                return ResourceManager.GetString("Invoice_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hóa đơn.
        /// </summary>
        public static string Invoice_Number {
            get {
                return ResourceManager.GetString("Invoice_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lần TT.
        /// </summary>
        public static string Invoice_PaymentPeriod {
            get {
                return ResourceManager.GetString("Invoice_PaymentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GT trước thuế.
        /// </summary>
        public static string Invoice_PretaxValue {
            get {
                return ResourceManager.GetString("Invoice_PretaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hóa đơn.
        /// </summary>
        public static string Invoice_ReleaseDate {
            get {
                return ResourceManager.GetString("Invoice_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế GTGT.
        /// </summary>
        public static string Invoice_VatValue {
            get {
                return ResourceManager.GetString("Invoice_VatValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn.
        /// </summary>
        public static string InvoicePlural {
            get {
                return ResourceManager.GetString("InvoicePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lần TT.
        /// </summary>
        public static string PaymentPeriod {
            get {
                return ResourceManager.GetString("PaymentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nghiệm thu.
        /// </summary>
        public static string PaymentPeriod_AcceptedDate {
            get {
                return ResourceManager.GetString("PaymentPeriod_AcceptedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp Đồng.
        /// </summary>
        public static string PaymentPeriod_Contract {
            get {
                return ResourceManager.GetString("PaymentPeriod_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string PaymentPeriod_CreatedAt {
            get {
                return ResourceManager.GetString("PaymentPeriod_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string PaymentPeriod_CreatedBy {
            get {
                return ResourceManager.GetString("PaymentPeriod_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô Tả.
        /// </summary>
        public static string PaymentPeriod_Description {
            get {
                return ResourceManager.GetString("PaymentPeriod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string PaymentPeriod_IsActive {
            get {
                return ResourceManager.GetString("PaymentPeriod_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string PaymentPeriod_ModifiedAt {
            get {
                return ResourceManager.GetString("PaymentPeriod_ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string PaymentPeriod_ModifiedBy {
            get {
                return ResourceManager.GetString("PaymentPeriod_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Lần TT.
        /// </summary>
        public static string PaymentPeriod_Name {
            get {
                return ResourceManager.GetString("PaymentPeriod_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ Tự.
        /// </summary>
        public static string PaymentPeriod_Order {
            get {
                return ResourceManager.GetString("PaymentPeriod_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Thanh Toán.
        /// </summary>
        public static string PaymentPeriod_PaidDate {
            get {
                return ResourceManager.GetString("PaymentPeriod_PaidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu TT.
        /// </summary>
        public static string PaymentPeriod_PaymentType {
            get {
                return ResourceManager.GetString("PaymentPeriod_PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Đề Nghị.
        /// </summary>
        public static string PaymentPeriod_RequestedDate {
            get {
                return ResourceManager.GetString("PaymentPeriod_RequestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá Trị NTHT.
        /// </summary>
        public static string PaymentPeriod_ValueAccepted {
            get {
                return ResourceManager.GetString("PaymentPeriod_ValueAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Tiền Thanh Toán.
        /// </summary>
        public static string PaymentPeriod_ValuePaid {
            get {
                return ResourceManager.GetString("PaymentPeriod_ValuePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Tiền Đề Nghị.
        /// </summary>
        public static string PaymentPeriod_ValueRequested {
            get {
                return ResourceManager.GetString("PaymentPeriod_ValueRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lần Thanh Toán.
        /// </summary>
        public static string PaymentPeriodPlural {
            get {
                return ResourceManager.GetString("PaymentPeriodPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu TT.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string PaymentType_CreatedAt {
            get {
                return ResourceManager.GetString("PaymentType_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string PaymentType_CreatedBy {
            get {
                return ResourceManager.GetString("PaymentType_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string PaymentType_Description {
            get {
                return ResourceManager.GetString("PaymentType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string PaymentType_IsActive {
            get {
                return ResourceManager.GetString("PaymentType_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string PaymentType_ModifiedAt {
            get {
                return ResourceManager.GetString("PaymentType_ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string PaymentType_ModifiedBy {
            get {
                return ResourceManager.GetString("PaymentType_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu Thanh Toán.
        /// </summary>
        public static string PaymentType_Name {
            get {
                return ResourceManager.GetString("PaymentType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu Thanh Toán.
        /// </summary>
        public static string PaymentTypePlural {
            get {
                return ResourceManager.GetString("PaymentTypePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự Án.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Dự Án.
        /// </summary>
        public static string Project_Code {
            get {
                return ResourceManager.GetString("Project_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string Project_CreatedAt {
            get {
                return ResourceManager.GetString("Project_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string Project_CreatedBy {
            get {
                return ResourceManager.GetString("Project_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Hoàn Công.
        /// </summary>
        public static string Project_EndDate {
            get {
                return ResourceManager.GetString("Project_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string Project_IsActive {
            get {
                return ResourceManager.GetString("Project_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string Project_ModifiedAt {
            get {
                return ResourceManager.GetString("Project_ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string Project_ModifiedBy {
            get {
                return ResourceManager.GetString("Project_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Dự Án.
        /// </summary>
        public static string Project_Name {
            get {
                return ResourceManager.GetString("Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Khởi Công.
        /// </summary>
        public static string Project_StartDate {
            get {
                return ResourceManager.GetString("Project_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự Án.
        /// </summary>
        public static string ProjectPlural {
            get {
                return ResourceManager.GetString("ProjectPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string User_Login {
            get {
                return ResourceManager.GetString("User_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string UserPlural {
            get {
                return ResourceManager.GetString("UserPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạng Mục.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại Chi Phí.
        /// </summary>
        public static string Work_CostType {
            get {
                return ResourceManager.GetString("Work_CostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string Work_CreatedAt {
            get {
                return ResourceManager.GetString("Work_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string Work_CreatedBy {
            get {
                return ResourceManager.GetString("Work_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string Work_IsActive {
            get {
                return ResourceManager.GetString("Work_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string Work_ModifiedAt {
            get {
                return ResourceManager.GetString("Work_ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string Work_ModifiedBy {
            get {
                return ResourceManager.GetString("Work_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Hạng Mục.
        /// </summary>
        public static string Work_Name {
            get {
                return ResourceManager.GetString("Work_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạng Mục Cha.
        /// </summary>
        public static string Work_ParentWork {
            get {
                return ResourceManager.GetString("Work_ParentWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự Án.
        /// </summary>
        public static string Work_Project {
            get {
                return ResourceManager.GetString("Work_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạng Mục.
        /// </summary>
        public static string WorkPlural {
            get {
                return ResourceManager.GetString("WorkPlural", resourceCulture);
            }
        }
    }
}
